#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : exdes.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Mar 26 11:17:24 +0100 2021
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: exdes.sh [-help]
# usage: exdes.sh [-lib_map_path]
# usage: exdes.sh [-noclean_files]
# usage: exdes.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'exdes.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm vid_phy_controller_v2_2_7 xil_defaultlib xlconstant_v1_1_7 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_22 v_hdmi_tx_v3_0_0 axi_lite_ipif_v3_0_4 v_tc_v6_2_1 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_11 util_vector_logic_v2_0_1 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 v_hdmi_rx_v3_0_0 v_tpg_v8_1_0 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_24 xlconcat_v2_1_4 proc_sys_reset_v5_0_13 lib_pkg_v1_0_2 axi_iic_v2_0_25 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "exdes.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work vid_phy_controller_v2_2_7 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/vhd/nidru_20_v_7.vhd" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/vhd/bs_flex_v_2.vhd" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/vhd/nidru_20_wrapper.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work vid_phy_controller_v2_2_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_lib.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_sync_block.v" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_sync_pulse.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_gtxe2_hdmi_txaln.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_gtxe2_hdmi_xcvr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_cpll_railing.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_datawidth_conv.sv" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_gt_tx_tmdsclk_patgen.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_clkdet.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_dru.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_axi4lite.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_gt_usrclk_source.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_gt_usrclk_source_8series.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_drp_control.v" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_drp_control_8series.v" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_drp_control_hdmi.v" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_interrupts.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_CLOCK_MODULE.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_CLOCK_MODULE_8series.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_plle2_drp.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_mmcme2_drp.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/hdl/src/verilog/exdes_vid_phy_controller_0_mmcme3_drp.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/exdes_vid_phy_controller_0_gtwizard_0_common.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vid_phy_controller_v2_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog/vid_phy_controller_v2_2_gtp_common.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/synth/exdes_vid_phy_controller_0_top.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vid_phy_controller_0/sim/exdes_vid_phy_controller_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_vcc_const_0/sim/exdes_vcc_const_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_tx_video_axis_reg_slice_0/sim/exdes_tx_video_axis_reg_slice_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_hdmi_tx_v3_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/2142/hdl/v_hdmi_tx_v3_0_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_0/sim/bd_3ea7_v_hdmi_tx_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_1/sim/bd_3ea7_v_tc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_2/sim/bd_3ea7_v_axi4s_vid_out_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/3f90/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_3/sim/bd_3ea7_util_vector_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_4/sim/bd_3ea7_axi_crossbar_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/sim/bd_3ea7.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_tx_ss_0/sim/exdes_v_hdmi_tx_ss_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_hdmi_rx_v3_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/a2bc/hdl/v_hdmi_rx_v3_0_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_0/sim/bd_3ec1_v_hdmi_rx_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_1/sim/bd_3ec1_v_vid_in_axi4s_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_2/sim/bd_3ec1_inverter_0_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_3/sim/bd_3ec1_inverter_1_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/sim/bd_3ec1.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_hdmi_rx_ss_0/sim/exdes_v_hdmi_rx_ss_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_rx_video_axis_reg_slice_0/sim/exdes_rx_video_axis_reg_slice_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_gnd_const_0/sim/exdes_gnd_const_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/exdes/ip/exdes_gt_refclk_buf1_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_gt_refclk_buf1_0/sim/exdes_gt_refclk_buf1_0.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_gt_refclk_buf0_0/sim/exdes_gt_refclk_buf0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_tpg_v8_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ip/exdes_v_tpg_0/hdl/v_tpg_v8_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_v_tpg_0/sim/exdes_v_tpg_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/exdes/ip/exdes_axi_gpio_0/sim/exdes_axi_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_xbar_0/sim/exdes_xbar_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0_mmcm_pll_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/proc_common_v3_00_a/hdl/src/vhdl/exdes_clk_wiz_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/proc_common_v3_00_a/hdl/src/vhdl/exdes_clk_wiz_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/proc_common_v3_00_a/hdl/src/vhdl/exdes_clk_wiz_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/proc_common_v3_00_a/hdl/src/vhdl/exdes_clk_wiz_0_family_support.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/proc_common_v3_00_a/hdl/src/vhdl/exdes_clk_wiz_0_family.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/proc_common_v3_00_a/hdl/src/vhdl/exdes_clk_wiz_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/proc_common_v3_00_a/hdl/src/vhdl/exdes_clk_wiz_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/exdes_clk_wiz_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/exdes_clk_wiz_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/exdes_clk_wiz_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0_clk_wiz_drp.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_aud_pat_gen_0/sim/exdes_aud_pat_gen_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_hdmi_acr_ctrl_0/sim/exdes_hdmi_acr_ctrl_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_xbar_1/sim/exdes_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_xlconcat_0/sim/exdes_xlconcat_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/exdes/ip/exdes_rst_processor_1_100M_0/sim/exdes_rst_processor_1_100M_0.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_rst_processor_1_300M_0/sim/exdes_rst_processor_1_300M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_1/exdes_clk_wiz_1_clk_wiz.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_clk_wiz_1/exdes_clk_wiz_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_25 $vhdlan_opts \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/1529/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/exdes/ip/exdes_fmch_axi_iic_0/sim/exdes_fmch_axi_iic_0.vhd" \
    "$ref_dir/../../../bd/exdes/ip/exdes_onbrd_axi_iic_0/sim/exdes_onbrd_axi_iic_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_zynq_0/sim/exdes_zynq_0.v" \
    "$ref_dir/../../../bd/exdes/ipshared/edit_Stereovision_v1_0.srcs/sources_1/imports/sources_1/new/Inter_col_v1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ipshared/edit_Stereovision_v1_0.srcs/sources_1/imports/sources_1/imports/Ncnx_Xppc/Ncntx_Xppc.sv" \
    "$ref_dir/../../../bd/exdes/ipshared/edit_Stereovision_v1_0.srcs/sources_1/imports/sources_1/new/SAD/SAD.sv" \
    "$ref_dir/../../../bd/exdes/ipshared/edit_Stereovision_v1_0.srcs/sources_1/imports/sources_1/new/SAD/SAD_v1_0.sv" \
    "$ref_dir/../../../bd/exdes/ipshared/edit_Stereovision_v1_0.srcs/sources_1/imports/sources_1/new/Stereovision.sv" \
    "$ref_dir/../../../bd/exdes/ipshared/edit_Stereovision_v1_0.srcs/sources_1/imports/sources_1/imports/Ncnx_Xppc/delay.sv" \
    "$ref_dir/../../../bd/exdes/ipshared/edit_Stereovision_v1_0.srcs/sources_1/imports/sources_1/imports/Ncnx_Xppc/delayLineBRAM_Xppc.sv" \
    "$ref_dir/../../../bd/exdes/ipshared/edit_Stereovision_v1_0.srcs/sources_1/imports/sources_1/imports/Ncnx_Xppc/delay_line.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ipshared/43ae/src/RGB_to_Grayscale_v1_0.v" \
    "$ref_dir/../../../bd/exdes/ipshared/43ae/hdl/Stereovision_v1_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_Stereovision_0_0/sim/exdes_Stereovision_0_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_xlconcat_0_0/sim/exdes_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_0/sim/exdes_auto_pc_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_8/sim/exdes_auto_pc_8.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_1/sim/exdes_auto_pc_1.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_2/sim/exdes_auto_pc_2.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_3/sim/exdes_auto_pc_3.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_4/sim/exdes_auto_pc_4.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_5/sim/exdes_auto_pc_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/9640/hdl/src/verilog" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/d0f7" +incdir+"$ref_dir/../../../../v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_cc_0/sim/exdes_auto_cc_0.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_6/sim/exdes_auto_pc_6.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_cc_1/sim/exdes_auto_cc_1.v" \
    "$ref_dir/../../../bd/exdes/ip/exdes_auto_pc_7/sim/exdes_auto_pc_7.v" \
    "$ref_dir/../../../bd/exdes/sim/exdes.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.exdes xil_defaultlib.glbl -o exdes_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./exdes_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./exdes.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key exdes_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc exdes_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./exdes.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: exdes.sh [-help]\n\
Usage: exdes.sh [-lib_map_path]\n\
Usage: exdes.sh [-reset_run]\n\
Usage: exdes.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
