
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[XPAR_XIIC_NUM_INSTANCES] =
{
	{
		XPAR_ZYNQ_SS_0_FMCH_AXI_IIC_DEVICE_ID,
		XPAR_ZYNQ_SS_0_FMCH_AXI_IIC_BASEADDR,
		XPAR_ZYNQ_SS_0_FMCH_AXI_IIC_TEN_BIT_ADR,
		XPAR_ZYNQ_SS_0_FMCH_AXI_IIC_GPO_WIDTH
	},
	{
		XPAR_ZYNQ_SS_0_ONBRD_AXI_IIC_DEVICE_ID,
		XPAR_ZYNQ_SS_0_ONBRD_AXI_IIC_BASEADDR,
		XPAR_ZYNQ_SS_0_ONBRD_AXI_IIC_TEN_BIT_ADR,
		XPAR_ZYNQ_SS_0_ONBRD_AXI_IIC_GPO_WIDTH
	}
};


