
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv_hdmirx.h"

/*
* The configuration table for devices
*/

XV_HdmiRx_Config XV_HdmiRx_ConfigTable[XPAR_XV_HDMIRX_NUM_INSTANCES] =
{
	{
		XPAR_V_HDMI_RX_SS_V_HDMI_RX_DEVICE_ID,
		XPAR_V_HDMI_RX_SS_V_HDMI_RX_BASEADDR,
		XPAR_V_HDMI_RX_SS_V_HDMI_RX_AXI_LITE_FREQ_HZ
	}
};


